motors:
  # motors order always in of pitch, yaw format
  motorIds:
    - 1
    - 2

  # reduction
  motorReduction:
    - 10
    - 8

  # limts
  accelerationLimits:
    - .5
    - .25

vision:
  # camara parameters
  cameraID: 0

detection:
  threshold: 0.8
  modelPath: "weights/yolo26n.pt"